dist: bionic
language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
- DJANGO_DATABASE_TEST=sqlite
- DJANGO_DATABASE_TEST=postgres

before_install:
  - sudo apt-get install gdal-bin libproj-dev libsqlite3-mod-spatialite -y
  - if [[ $DJANGO_DATABASE_TEST == postgres ]]; then sudo apt-get install -y postgresql-12-postgis-3; fi
  - if [[ $DJANGO_DATABASE_TEST == postgres ]]; then sudo cp /etc/postgresql/{10,12}/main/pg_hba.conf; fi
  - if [[ $DJANGO_DATABASE_TEST == postgres ]]; then sudo systemctl restart postgresql@12-main; fi
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"
  - cp findyourhappiness/local_settings.py.template findyourhappiness/local_settings.py

install: 
  - poetry install

script: 
  - make lint
  - make test

after_success:
  - pip install coveralls
  - coveralls