# Generated by Django 3.0 on 2019-12-11 06:57

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('index', '0002_place_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='cat',
            new_name='type_place',
        ),
        migrations.AddField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(to='index.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
