# Generated by Django 3.0 on 2019-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191211_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='c_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='c_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='wd_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
