# Generated by Django 3.0 on 2019-12-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191211_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Region', verbose_name='Регион'),
        ),
    ]
