# Generated by Django 3.0 on 2019-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191212_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
        migrations.AddField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
