# Generated by Django 3.0 on 2019-12-12 07:11

import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20191212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=imagefield.fields.ImageField(blank=True, height_field='image_height', upload_to='', verbose_name='Изображение', width_field='image_width'),
        ),
    ]
