# Generated by Django 3.0 on 2019-12-13 00:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20191212_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='c_lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='c_lon',
        ),
        migrations.RemoveField(
            model_name='place',
            name='c_lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='c_lon',
        ),
        migrations.AddField(
            model_name='city',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='place',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
    ]
