# Generated by Django 3.0 on 2019-12-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20191213_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='title_pl',
            field=models.CharField(default='', max_length=200, verbose_name='Множественное название'),
            preserve_default=False,
        ),
    ]
