# Generated by Django 3.0 on 2019-12-17 07:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_place_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Маршрут')),
                ('leight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rt_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.City', verbose_name='Начальный пункт')),
                ('rt_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Place', verbose_name='Конечный пункт')),
            ],
        ),
    ]
