# Generated by Django 3.0 on 2019-12-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AddField(
            model_name='route',
            name='rt_type',
            field=models.CharField(blank=True, choices=[('w', 'Водный'), ('a', 'Автомобильный'), ('h', 'Пеший')], default='h', max_length=1, verbose_name='Тип маршрута'),
        ),
    ]
