# Generated by Django 3.0 on 2019-12-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20191217_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='leight',
            new_name='rt_length',
        ),
    ]
