# Generated by Django 3.0 on 2019-12-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20191218_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rt_title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
