# Generated by Django 3.0 on 2019-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20191218_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='rt_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина'),
        ),
    ]
