# Generated by Django 3.0.1 on 2019-12-20 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_type_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Type', verbose_name='Категория'),
        ),
    ]
