# Generated by Django 3.0.1 on 2019-12-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_city_type_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='type_place',
        ),
    ]
