# Generated by Django 3.0.2 on 2020-01-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_remove_city_type_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['title'], 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['title'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
