# Generated by Django 3.0.2 on 2020-01-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20200115_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ig_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Локация в IG'),
        ),
    ]
