# Generated by Django 3.0.2 on 2020-01-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_place_ig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rt_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_city', to='index.City', verbose_name='Начальный пункт'),
        ),
        migrations.AlterField(
            model_name='route',
            name='rt_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_place', to='index.Place', verbose_name='Конечный пункт'),
        ),
    ]
