# Generated by Django 3.0.2 on 2020-01-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20200117_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='ls',
        ),
    ]
