# Generated by Django 3.0.2 on 2020-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20200117_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='rt_el_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Набор высоты'),
        ),
        migrations.AddField(
            model_name='route',
            name='rt_el_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Потеря высоты'),
        ),
        migrations.AddField(
            model_name='route',
            name='rt_is_gpx',
            field=models.BooleanField(default=False, verbose_name='GPX?'),
        ),
        migrations.AddField(
            model_name='route',
            name='rt_max_el',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Максимальная высота'),
        ),
        migrations.AddField(
            model_name='route',
            name='rt_min_el',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Минимальная высота'),
        ),
    ]
