# Generated by Django 3.0.2 on 2020-01-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20200120_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title_alt',
            field=models.CharField(blank=True, help_text='Например, Фалаза для горы Литовка.', max_length=200, verbose_name='Альтернативное название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Ближайший населённый пункт с которого начинаются основные маршруты.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.City', verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='place',
            name='ig_id',
            field=models.CharField(blank=True, help_text='Например, 771936715 для <a href="https://www.instagram.com/explore/locations/771936715/">гора Ольховая</a>.', max_length=20, verbose_name='Локация в IG'),
        ),
        migrations.AlterField(
            model_name='place',
            name='wd_id',
            field=models.CharField(blank=True, help_text='Например, Q4317189 для <a href="https://www.wikidata.org/wiki/Q4317189">водопад Неожиданный</a>.', max_length=10),
        ),
    ]
