# Generated by Django 3.0.2 on 2020-01-21 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20200120_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ig_id',
            field=models.CharField(blank=True, help_text='Например, 771936715 для <a href="https://www.instagram.com/explore/locations/771936715/">гора Ольховая</a>.', max_length=20, verbose_name='Локация в Инстаграме'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title_alt',
            field=models.CharField(blank=True, help_text='Другое распространённое название, иногда официальное название на картах. Например, Литовка для горы Фалаза.', max_length=200, verbose_name='Альтернативное название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='wd_id',
            field=models.CharField(blank=True, help_text='Например, Q4317189 для <a href="https://www.wikidata.org/wiki/Q4317189">водопад Неожиданный</a>.', max_length=10, validators=[django.core.validators.RegexValidator(regex='^Q([0-9]{1,9})$')], verbose_name='ID на Wikidata'),
        ),
    ]
