# Generated by Django 3.0.2 on 2020-01-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20200115_1154'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='favor_place',
            field=models.ManyToManyField(to='index.Place', verbose_name='Понравившиеся места'),
        ),
    ]
