# Generated by Django 3.0.2 on 2020-01-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20200115_1154'),
        ('user', '0002_auto_20200115_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='done_place',
            field=models.ManyToManyField(db_table='done_user_place', related_name='done_place', to='index.Place', verbose_name='Пройденные места'),
        ),
        migrations.AddField(
            model_name='profile',
            name='want_place',
            field=models.ManyToManyField(db_table='want_user_place', related_name='want_place', to='index.Place', verbose_name='Планируемые места'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favor_place',
            field=models.ManyToManyField(db_table='favor_user_place', related_name='favor_place', to='index.Place', verbose_name='Избранное'),
        ),
    ]
