# Generated by Django 3.0.2 on 2020-01-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20200115_1154'),
        ('user', '0003_auto_20200115_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favor_place',
        ),
        migrations.AddField(
            model_name='profile',
            name='like_place',
            field=models.ManyToManyField(db_table='like_user_place', related_name='like_place', to='index.Place', verbose_name='Избранное'),
        ),
    ]
