# Generated by Django 3.0.2 on 2020-01-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20200120_1555'),
        ('user', '0004_auto_20200115_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(help_text='Используется для показа пути от этого места до начала маршрута.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.City', verbose_name='Населённый пункт'),
        ),
    ]
