# Generated by Django 3.0.2 on 2020-01-21 07:47

from django.db import migrations, models
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200120_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=imagefield.fields.ImageField(blank=True, height_field='image_height', upload_to='', verbose_name='Изображение', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткая информация'),
        ),
    ]
